### ISSUE TITLE
Error compiling using Mac

### ISSUE THREAD

**Issue by michaelgold** [rfsheffer/QuestHands#4]
Hi Ryan,

I'm getting an error compiling the QuestHandsExample project on a Mac using the latest version of the Oculus UE4 branch (4.24.3). Everything compiles fine for me on Windows.

The specific error is below, and I'm wondering if you've seen anything like this before and can point me in the right direction:

```
Creating makefile for QuestHandsExample (.uproject file is newer)
While compiling /Users/admin/src/QuestHands/Intermediate/Build/BuildRules/QuestHandsExampleModuleRules.dll:
/Users/admin/src/QuestHands/Plugins/QuestHands/Source/QuestHands/QuestHands.Build.cs(1,1) : error CS1056: Unexpected character `›'
ERROR: Unable to compile source files.
The terminal process terminated with exit code: 5

Terminal will be reused by tasks, press any key to close it.

> Executing task in folder QuestHandsExample: Engine/Build/BatchFiles/Mac/Build.sh QuestHandsExample Mac Debug /Users/admin/src/QuestHands/QuestHandsExample.uproject -waitmutex <

Running bundled mono, version: Mono JIT compiler version 5.16.0.220 (2018-06/bb3ae37d71a Fri Nov 16 17:12:11 EST 2018)
Running command : Engine/Binaries/DotNET/UnrealBuildTool.exe QuestHandsExample Mac Debug /Users/admin/src/QuestHands/QuestHandsExample.uproject -waitmutex
Using 'git status' to determine working set for adaptive non-unity build (/Users/admin/src/UnrealEngine).
Using 'git status' to determine working set for adaptive non-unity build (/Users/admin/src/QuestHands).
Creating makefile for QuestHandsExample (.uproject file is newer)
WARNING: QuestHandsExample is configured for nativization, but is missing the generated code plugin at "/Users/admin/src/QuestHands/Intermediate/Plugins/NativizedAssets/Mac/Game/NativizedAssets.uplugin". Make sure to cook Game data before attempting to build the Mac target. If data was cooked with nativization enabled, this can also mean there were no Blueprint assets that required conversion, in which case this warning can be safely ignored.
ERROR: OculusVR.uplugin is referenced via default plugins -> QuestHands.uplugin with a mismatched 'SupportedTargetPlatforms' field. This will cause problems in packaged builds, because the .uplugin file will not be staged. Launch the editor to update references from your project file, or update references from other plugins manually.
The terminal process terminated with exit code: 5
```

**Comment by rfsheffer** [comment]
Sorry for the really late response.
I see two errors in your output:
**QuestHands.Build.cs(1,1) : error CS1056: Unexpected character `›'**
and
**ERROR: OculusVR.uplugin is referenced via default... bla bla**

The first one might be as easy as resaving the file QuestHands.Build.cs by opening it in a text editor on the mac and saving. Bad line endings?

The second one might be because I don't include the SupportedTargetPlatforms section in the plugin and the defaults doesn't align with the OVR plugin.
Add:
`"SupportedTargetPlatforms": [
		"Win32",
		"Win64",
		"Android"
	],`
To QuestHands.uplugin and give er a try.

Cheers!

**Comment by msgtobala** [comment]
I am facing a similar error. But I have the error with InterchangeEditor
InterchangeEditor.uplugin is referenced via MyProject.uproject with a mismatched 'SupportedTargetPlatforms' field. This will cause problems in packaged builds, because the .uplugin file will not be staged. Launch the editor to update references from your project file, or update references from other plugins manually.
BuildLogEventException: InterchangeEditor.uplugin is referenced via MyProject.uproject with a mismatched 'SupportedTargetPlatforms' field. This will cause problems in packaged builds, because the .uplugin file will not be staged. Launch the editor to update references from your project file, or update references from other plugins manually.
   at UnrealBuildTool.UEBuildTarget.AddPlugin(PluginReferenceDescriptor Reference, String ReferenceChain, String[] ExcludeFolders, Dictionary`2 NameToInstance, Dictionary`2 NameToInfos, ILogger Logger) in /Users/build/Build/++UE5/Sync/Engine/Saved/CsTools/Engine/Source/Programs/UnrealBuildTool/Configuration/UEBuildTarget.cs:line 4461
   at UnrealBuildTool.UEBuildTarget.SetupPlugins(ILogger Logger) in /Users/build/Build/++UE5/Sync/Engine/Saved/CsTools/Engine/Source/Programs/UnrealBuildTool/Configuration/UEBuildTarget.cs:line 4285
   at UnrealBuildTool.UEBuildTarget.PreBuildSetup(ILogger Logger) in /Users/build/Build/++UE5/Sync/Engine/Saved/CsTools/Engine/Source/Programs/UnrealBuildTool/Configuration/UEBuildTarget.cs:line 3316
   at UnrealBuildTool.UEBuildTarget.Create(TargetDescriptor Descriptor, Boolean bSkipRulesCompile, Boolean bForceRulesCompile, Boolean bUsePrecompiled, UnrealIntermediateEnvironment IntermediateEnvironment, ILogger Logger) in /Users/build/Build/++UE5/Sync/Engine/Saved/CsTools/Engine/Source/Programs/UnrealBuildTool/Configuration/UEBuildTarget.cs:line 1366
   at UnrealBuildTool.BuildMode.CreateMakefileAsync(BuildConfiguration BuildConfiguration, TargetDescriptor TargetDescriptor, ISourceFileWorkingSet WorkingSet, ILogger Logger) in /Users/build/Build/++UE5/Sync/Engine/Saved/CsTools/Engine/Source/Programs/UnrealBuildTool/Modes/BuildMode.cs:line 1114
   at UnrealBuildTool.BuildMode.BuildAsync(List`1 TargetDescriptors, BuildConfiguration BuildConfiguration, ISourceFileWorkingSet WorkingSet, BuildOptions Options, FileReference WriteOutdatedActionsFile, ILogger Logger, Boolean bSkipPreBuildTargets) in /Users/build/Build/++UE5/Sync/Engine/Saved/CsTools/Engine/Source/Programs/UnrealBuildTool/Modes/BuildMode.cs:line 396
   at UnrealBuildTool.BuildMode.ExecuteAsync(CommandLineArguments Arguments, ILogger Logger) in /Users/build/Build/++UE5/Sync/Engine/Saved/CsTools/Engine/Source/Programs/UnrealBuildTool/Modes/BuildMode.cs:line 252
   at UnrealBuildTool.UnrealBuildTool.Main(String[] ArgumentsArray) in /Users/build/Build/++UE5/Sync/Engine/Saved/CsTools/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.cs:line 659
WriteFileIfChanged() wrote 0 changed files of 0 requested writes.

**Comment by akshay-nm** [comment]
were you able to fix it @msgtobala ?
